# -*- coding: utf-8 -*-
"""prithvi-eo-2.0-inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvTYeUQySjLuQbMRwOi_w612UBCKcqge
"""

!nvidia-smi

!pip install -q --no-cache-dir --force-reinstall "numpy==2.2.6" "scipy==1.16.2" "terratorch>=1.1"
!python -c "import numpy as np, scipy; print('NumPy:', np.__version__); print('SciPy:', scipy.__version__); from terratorch.registry import BACKBONE_REGISTRY; print('Terratorch import OK')"

import numpy as np
import scipy

print("NumPy:", np.__version__)
print("SciPy:", scipy.__version__)

import numpy as np
import scipy
import sys

print("NumPy version:", np.__version__)
print("NumPy path:", np.__file__)
print("SciPy version:", scipy.__version__)
print("SciPy path:", scipy.__file__)
print("Python executable:", sys.executable)

!pip show numpy scipy

import numpy as np
import scipy

print("NumPy:", np.__version__)
print("SciPy:", scipy.__version__)

!python -m pip show numpy scipy
!python - <<'PY'
import numpy as np, scipy, sys
print("Python:", sys.executable)
print("NumPy imported version:", np.__version__)
print("NumPy file:", np.__file__)
print("SciPy imported version:", scipy.__version__)
print("SciPy file:", scipy.__file__)
PY

!python -c "import torch; from terratorch.registry import BACKBONE_REGISTRY; model = BACKBONE_REGISTRY.build('prithvi_eo_v2_tiny_tl', pretrained=True); print(type(model)); print('Params:', sum(p.numel() for p in model.parameters())); print('CUDA available:', torch.cuda.is_available())"

!python - <<'PY'
import inspect
from terratorch.registry import BACKBONE_REGISTRY

model = BACKBONE_REGISTRY.build("prithvi_eo_v2_tiny_tl", pretrained=True)

print("Model class:", type(model))
print("\nForward signature:")
print(inspect.signature(model.forward))

print("\nPublic attributes:")
for name in dir(model):
    if not name.startswith("_"):
        if name in ["img_size", "patch_size", "in_chans", "num_frames", "embed_dim"]:
            print(name, "=", getattr(model, name))
PY

import subprocess, sys, textwrap

code = textwrap.dedent("""
import torch
from terratorch.registry import BACKBONE_REGISTRY

model = BACKBONE_REGISTRY.build("prithvi_eo_v2_tiny_tl", pretrained=True)
model.eval()

test_inputs = {
    "B,C,H,W": torch.randn(1, 6, 224, 224),
    "B,C,T,H,W": torch.randn(1, 6, 1, 224, 224),
    "B,T,C,H,W": torch.randn(1, 1, 6, 224, 224),
}

for name, x in test_inputs.items():
    print(f"\\nTrying shape {name}: {tuple(x.shape)}")
    try:
        with torch.no_grad():
            y = model(x)
        print("SUCCESS")
        print("Output type:", type(y))
        if hasattr(y, "shape"):
            print("Output shape:", y.shape)
        elif isinstance(y, (list, tuple)):
            print("Output length:", len(y))
            for i, item in enumerate(y):
                if hasattr(item, "shape"):
                    print(f"  item {i} shape: {item.shape}")
                else:
                    print(f"  item {i} type: {type(item)}")
        else:
            print("Output:", y)
    except Exception as e:
        print("FAILED")
        print(type(e).__name__ + ":", e)
""")

result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

import subprocess, sys, textwrap

code = textwrap.dedent("""
from terratorch.registry import BACKBONE_REGISTRY

names = sorted(BACKBONE_REGISTRY.registry.keys())
prithvi_names = [n for n in names if "prithvi" in n.lower()]

print("Available Prithvi backbones:")
for n in prithvi_names:
    print("-", n)
""")

result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

import subprocess, sys, textwrap

code = textwrap.dedent("""
from terratorch.registry import BACKBONE_REGISTRY

print("Type:", type(BACKBONE_REGISTRY))
print("\\nAttributes/methods:")
for name in dir(BACKBONE_REGISTRY):
    if not name.startswith("_"):
        print(name)
""")

result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

import subprocess, sys, textwrap

code = textwrap.dedent("""
from terratorch.registry import BACKBONE_REGISTRY

names = sorted(list(BACKBONE_REGISTRY.keys()))
prithvi_names = [n for n in names if "prithvi" in n.lower()]

print("Available Prithvi backbones:")
for n in prithvi_names:
    print("-", n)
""")

result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

import subprocess, sys, textwrap

code = textwrap.dedent("""
from terratorch.registry import BACKBONE_REGISTRY

candidate_names = [
    "prithvi_eo_v2_tiny_tl",
    "prithvi_eo_v2_tiny",
    "prithvi_eo_v2_100_tl",
    "prithvi_eo_v2_100",
    "prithvi_eo_v2_300_tl",
    "prithvi_eo_v2_300",
]

for name in candidate_names:
    print(f"\\nTesting: {name}")
    try:
        obj = BACKBONE_REGISTRY.get(name)
        print("get() ->", obj)
    except Exception as e:
        print("get() failed:", type(e).__name__, e)

    try:
        reg = BACKBONE_REGISTRY.find_registry(name)
        print("find_registry() ->", reg)
    except Exception as e:
        print("find_registry() failed:", type(e).__name__, e)
""")

result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

!rm -rf Prithvi-EO-2.0
!git clone https://github.com/NASA-IMPACT/Prithvi-EO-2.0.git
!ls Prithvi-EO-2.0

!find Prithvi-EO-2.0 -maxdepth 4 \( -iname "*infer*" -o -iname "*reconstruct*" -o -iname "*inference*" -o -iname "*mask*" \) | sort

!find Prithvi-EO-2.0/examples Prithvi-EO-2.0/configs -type f | sort

!python - <<'PY'
from huggingface_hub import list_repo_files

repo_id = "ibm-nasa-geospatial/Prithvi-EO-2.0-tiny-TL"
files = list_repo_files(repo_id, repo_type="model")

for f in files:
    print(f)
PY

from huggingface_hub import hf_hub_download

repo_id = "ibm-nasa-geospatial/Prithvi-EO-2.0-tiny-TL"
local_path = hf_hub_download(repo_id=repo_id, filename="inference.py")
print(local_path)

with open(local_path, "r") as f:
    for i, line in enumerate(f, 1):
        if i > 220:
            break
        print(f"{i:03d}: {line}", end="")

local_path = "/root/.cache/huggingface/hub/models--ibm-nasa-geospatial--Prithvi-EO-2.0-tiny-TL/snapshots/335eadc2c45ad5abe7bd307223e1c48c5b60c41b/inference.py"

with open(local_path, "r") as f:
    lines = f.readlines()

for i, line in enumerate(lines[220:420], 221):
    print(f"{i:03d}: {line}", end="")

local_path = "/root/.cache/huggingface/hub/models--ibm-nasa-geospatial--Prithvi-EO-2.0-tiny-TL/snapshots/335eadc2c45ad5abe7bd307223e1c48c5b60c41b/inference.py"

with open(local_path, "r") as f:
    lines = f.readlines()

for i, line in enumerate(lines[420:], 421):
    print(f"{i:03d}: {line}", end="")

from huggingface_hub import snapshot_download
import os

local_dir = "/content/prithvi_tiny_infer"

snapshot_download(
    repo_id="ibm-nasa-geospatial/Prithvi-EO-2.0-tiny-TL",
    local_dir=local_dir,
    local_dir_use_symlinks=False,
    allow_patterns=[
        "inference.py",
        "prithvi_mae.py",
        "config.json",
        "Prithvi_EO_V2_tiny_TL.pt",
        "examples/*.tif",
    ],
)

for root, dirs, files in os.walk(local_dir):
    level = root.replace(local_dir, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")
    for f in sorted(files):
        print(f"{indent}  {f}")

!cd /content/prithvi_tiny_infer && python inference.py --rgb_outputs --output_dir output_example && find output_example -maxdepth 1 -type f | sort

from pathlib import Path

p = Path("/content/prithvi_tiny_infer/inference.py")
text = p.read_text()

text = text.replace(
    'temporal_coords = torch.Tensor(temporal_coords, device=device).unsqueeze(0)',
    'temporal_coords = torch.tensor(temporal_coords, dtype=torch.float32, device=device).unsqueeze(0)'
)

text = text.replace(
    'location_coords = torch.Tensor(location_coords[0], device=device).unsqueeze(0)',
    'location_coords = torch.tensor(location_coords[0], dtype=torch.float32, device=device).unsqueeze(0)'
)

p.write_text(text)

with open(p, "r") as f:
    lines = f.readlines()

for i in range(395, 401):
    print(f"{i+1}: {lines[i]}", end="")

import os
import rasterio
import matplotlib.pyplot as plt

base = "/content/prithvi_tiny_infer/output_example"

def read_rgb(path):
    with rasterio.open(path) as src:
        img = src.read()  # (3, H, W)
    return img.transpose(1, 2, 0)  # (H, W, 3)

fig, axes = plt.subplots(4, 3, figsize=(12, 16))

for t in range(4):
    orig = read_rgb(os.path.join(base, f"original_rgb_t{t}.tiff"))
    mask = read_rgb(os.path.join(base, f"masked_rgb_t{t}.tiff"))
    pred = read_rgb(os.path.join(base, f"predicted_rgb_t{t}.tiff"))

    axes[t, 0].imshow(orig)
    axes[t, 0].set_title(f"t{t} original")
    axes[t, 0].axis("off")

    axes[t, 1].imshow(mask)
    axes[t, 1].set_title(f"t{t} masked")
    axes[t, 1].axis("off")

    axes[t, 2].imshow(pred)
    axes[t, 2].set_title(f"t{t} predicted")
    axes[t, 2].axis("off")

plt.tight_layout()
plt.show()

import os

path = "/content/prithvi_tiny_infer/prithvi_mae.py"

keywords = ["def forward", "random_mask", "mask_ratio", "mask", "unpatchify"]
with open(path, "r") as f:
    lines = f.readlines()

for i, line in enumerate(lines, 1):
    low = line.lower()
    if any(k.lower() in low for k in keywords):
        start = max(1, i - 3)
        end = min(len(lines), i + 8)
        print(f"\n--- lines {start} to {end} ---")
        for j in range(start, end + 1):
            print(f"{j:03d}: {lines[j-1]}", end="")

from pathlib import Path

p = Path("/content/prithvi_tiny_infer/prithvi_mae.py")
text = p.read_text()

text = text.replace(
    "        self, x: torch.Tensor,\n        temporal_coords: None | torch.Tensor = None,\n        location_coords: None | torch.Tensor = None,\n        mask_ratio=0.75\n    ):",
    "        self, x: torch.Tensor,\n        temporal_coords: None | torch.Tensor = None,\n        location_coords: None | torch.Tensor = None,\n        mask_ratio=0.75,\n        noise: torch.Tensor | None = None,\n    ):"
)

text = text.replace(
    "        x, mask, ids_restore = self.random_masking(x, mask_ratio)",
    "        x, mask, ids_restore = self.random_masking(x, mask_ratio, noise=noise)"
)

text = text.replace(
    "        self,\n        pixel_values: torch.Tensor,\n        temporal_coords: None | torch.Tensor = None,\n        location_coords: None | torch.Tensor = None,\n        mask_ratio: float = None,\n    ):",
    "        self,\n        pixel_values: torch.Tensor,\n        temporal_coords: None | torch.Tensor = None,\n        location_coords: None | torch.Tensor = None,\n        mask_ratio: float = None,\n        noise: torch.Tensor | None = None,\n    ):"
)

text = text.replace(
    "        latent, mask, ids_restore = self.encoder(pixel_values, temporal_coords, location_coords, mask_ratio)",
    "        latent, mask, ids_restore = self.encoder(pixel_values, temporal_coords, location_coords, mask_ratio, noise=noise)"
)

p.write_text(text)

with open(p, "r") as f:
    lines = f.readlines()

for i in range(390, 420):
    print(f"{i+1}: {lines[i]}", end="")

print("\n" + "="*60 + "\n")

for i in range(742, 758):
    print(f"{i+1}: {lines[i]}", end="")

import sys, os, yaml, torch, numpy as np
sys.path.insert(0, "/content/prithvi_tiny_infer")

from prithvi_mae import PrithviMAE
from inference import load_example

# -----------------------------
# paths
# -----------------------------
base = "/content/prithvi_tiny_infer"
config_path = os.path.join(base, "config.json")
checkpoint = os.path.join(base, "Prithvi_EO_V2_tiny_TL.pt")
data_files = [
    os.path.join(base, "examples", "Mexico_HLS.S30.T13REM.2018026T173609.v2.0_cropped.tif"),
    os.path.join(base, "examples", "Mexico_HLS.S30.T13REM.2018106T172859.v2.0_cropped.tif"),
    os.path.join(base, "examples", "Mexico_HLS.S30.T13REM.2018201T172901.v2.0_cropped.tif"),
    os.path.join(base, "examples", "Mexico_HLS.S30.T13REM.2018266T173029.v2.0_cropped.tif"),
]

# -----------------------------
# load config + model
# -----------------------------
with open(config_path, "r") as f:
    config = yaml.safe_load(f)["pretrained_cfg"]

bands = config["bands"]
mean = config["mean"]
std = config["std"]
coords_encoding = config["coords_encoding"]
img_size = config["img_size"]
num_frames = len(data_files)

config.update(
    coords_encoding=coords_encoding,
    num_frames=num_frames,
    in_chans=len(bands),
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PrithviMAE(**config).to(device)

state_dict = torch.load(checkpoint, map_location=device, weights_only=True)
for k in list(state_dict.keys()):
    if k == "encoder.pos_embed":
        state_dict[k] = model.encoder.pos_embed
    elif k == "decoder.decoder_pos_embed":
        state_dict[k] = model.decoder.decoder_pos_embed
model.load_state_dict(state_dict, strict=True)
model.eval()

# -----------------------------
# load one sample
# -----------------------------
input_data, temporal_coords, location_coords, meta_data = load_example(
    file_paths=data_files, mean=mean, std=std
)

# one 224x224 window is enough for this sanity check
x = torch.tensor(input_data, dtype=torch.float32, device=device)   # (1, C, T, H, W)
temporal_coords = torch.tensor(temporal_coords, dtype=torch.float32, device=device).unsqueeze(0)
location_coords = torch.tensor(location_coords[0], dtype=torch.float32, device=device).unsqueeze(0)

# -----------------------------
# build custom noise:
# mask whole frame t=1
# -----------------------------
frame_to_mask = 1
tokens_per_frame = (x.shape[-2] // 16) * (x.shape[-1] // 16)   # 14*14 = 196 for 224x224
seq_length = x.shape[2] * tokens_per_frame                     # 4 * 196 = 784
mask_ratio = 1.0 / x.shape[2]                                 # mask exactly one frame out of 4 = 0.25

noise = torch.zeros((1, seq_length), dtype=torch.float32, device=device)
start = frame_to_mask * tokens_per_frame
end = (frame_to_mask + 1) * tokens_per_frame
noise[:, start:end] = 1.0

# -----------------------------
# run model with custom frame mask
# -----------------------------
with torch.no_grad():
    loss, pred, mask = model(
        x,
        temporal_coords=temporal_coords,
        location_coords=location_coords,
        mask_ratio=mask_ratio,
        noise=noise,
    )

mask_by_frame = mask.view(1, x.shape[2], tokens_per_frame)[0]

print("Input shape:", tuple(x.shape))
print("tokens_per_frame:", tokens_per_frame)
print("seq_length:", seq_length)
print("mask_ratio:", mask_ratio)
print("frame_to_mask:", frame_to_mask)
print("mask shape:", tuple(mask.shape))
print("pred shape:", tuple(pred.shape))
print("loss:", float(loss))

print("\nMean mask value per frame (0 = kept, 1 = fully masked):")
for t in range(x.shape[2]):
    print(f"frame {t}: {mask_by_frame[t].float().mean().item():.4f}")

import matplotlib.pyplot as plt
import torch
import numpy as np

# -----------------------------
# rebuild reconstructed image
# -----------------------------
orig_h, orig_w = x.shape[-2], x.shape[-1]

mask_img = model.unpatchify(
    mask.unsqueeze(-1).repeat(1, 1, pred.shape[-1]).detach().cpu(),
    image_size=(orig_h, orig_w)
)

pred_img = model.unpatchify(
    pred.detach().cpu(),
    image_size=(orig_h, orig_w)
)

x_cpu = x.detach().cpu()

print("x_cpu shape:", tuple(x_cpu.shape))
print("mask_img shape:", tuple(mask_img.shape))
print("pred_img shape:", tuple(pred_img.shape))

rec_img = x_cpu.clone()
rec_img[mask_img == 1] = pred_img[mask_img == 1]

# -----------------------------
# choose RGB channels
# -----------------------------
rgb_channels = [bands.index("B04"), bands.index("B03"), bands.index("B02")]
mean_t = torch.tensor(np.asarray(mean)[:, None, None], dtype=torch.float32)
std_t = torch.tensor(np.asarray(std)[:, None, None], dtype=torch.float32)

def to_rgb(img_cthw, t):
    img = img_cthw[:, t, :, :].clone()
    img = (img * std_t) + mean_t
    img = img[rgb_channels, :, :]
    img = torch.clamp(img / 3000.0, 0, 1)
    return img.permute(1, 2, 0).numpy()

# -----------------------------
# plot originals vs reconstructed
# -----------------------------
fig, axes = plt.subplots(2, 4, figsize=(18, 9))

for t in range(x_cpu.shape[2]):
    axes[0, t].imshow(to_rgb(x_cpu[0], t))
    axes[0, t].set_title(f"original t{t}")
    axes[0, t].axis("off")

    axes[1, t].imshow(to_rgb(rec_img[0], t))
    title = f"reconstructed t{t}"
    if t == frame_to_mask:
        title += " <-- fully masked"
    axes[1, t].set_title(title)
    axes[1, t].axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import torch
import numpy as np

# -----------------------------
# choose two fully missing frames
# -----------------------------
frames_to_mask = [1, 3]   # like missing Feb and Apr
tokens_per_frame = (x.shape[-2] // 16) * (x.shape[-1] // 16)
seq_length = x.shape[2] * tokens_per_frame
mask_ratio = len(frames_to_mask) / x.shape[2]

noise = torch.zeros((1, seq_length), dtype=torch.float32, device=device)
for t in frames_to_mask:
    start = t * tokens_per_frame
    end = (t + 1) * tokens_per_frame
    noise[:, start:end] = 1.0

with torch.no_grad():
    loss2, pred2, mask2 = model(
        x,
        temporal_coords=temporal_coords,
        location_coords=location_coords,
        mask_ratio=mask_ratio,
        noise=noise,
    )

mask2_by_frame = mask2.view(1, x.shape[2], tokens_per_frame)[0]

print("mask_ratio:", mask_ratio)
print("loss:", float(loss2))
print("\nMean mask value per frame:")
for t in range(x.shape[2]):
    print(f"frame {t}: {mask2_by_frame[t].float().mean().item():.4f}")

# -----------------------------
# rebuild reconstructed images
# -----------------------------
orig_h, orig_w = x.shape[-2], x.shape[-1]

mask_img2 = model.unpatchify(
    mask2.unsqueeze(-1).repeat(1, 1, pred2.shape[-1]).detach().cpu(),
    image_size=(orig_h, orig_w)
)
pred_img2 = model.unpatchify(
    pred2.detach().cpu(),
    image_size=(orig_h, orig_w)
)

x_cpu = x.detach().cpu()
rec_img2 = x_cpu.clone()
rec_img2[mask_img2 == 1] = pred_img2[mask_img2 == 1]

# -----------------------------
# RGB visualization
# -----------------------------
rgb_channels = [bands.index("B04"), bands.index("B03"), bands.index("B02")]
mean_t = torch.tensor(np.asarray(mean)[:, None, None], dtype=torch.float32)
std_t = torch.tensor(np.asarray(std)[:, None, None], dtype=torch.float32)

def to_rgb(img_cthw, t):
    img = img_cthw[:, t, :, :].clone()
    img = (img * std_t) + mean_t
    img = img[rgb_channels, :, :]
    img = torch.clamp(img / 3000.0, 0, 1)
    return img.permute(1, 2, 0).numpy()

# -----------------------------
# simple error metric
# -----------------------------
print("\nPer-frame MAE in normalized input space:")
for t in range(x_cpu.shape[2]):
    mae = torch.mean(torch.abs(rec_img2[0, :, t] - x_cpu[0, :, t])).item()
    print(f"frame {t}: {mae:.6f}")

# -----------------------------
# plot
# -----------------------------
fig, axes = plt.subplots(2, 4, figsize=(18, 9))

for t in range(x_cpu.shape[2]):
    axes[0, t].imshow(to_rgb(x_cpu[0], t))
    axes[0, t].set_title(f"original t{t}")
    axes[0, t].axis("off")

    axes[1, t].imshow(to_rgb(rec_img2[0], t))
    title = f"reconstructed t{t}"
    if t in frames_to_mask:
        title += " <-- fully masked"
    axes[1, t].set_title(title)
    axes[1, t].axis("off")

plt.tight_layout()
plt.show()

results = []

tokens_per_frame = (x.shape[-2] // 16) * (x.shape[-1] // 16)
seq_length = x.shape[2] * tokens_per_frame

for frame_to_mask in range(x.shape[2]):
    noise = torch.zeros((1, seq_length), dtype=torch.float32, device=device)
    start = frame_to_mask * tokens_per_frame
    end = (frame_to_mask + 1) * tokens_per_frame
    noise[:, start:end] = 1.0

    with torch.no_grad():
        loss_s, pred_s, mask_s = model(
            x,
            temporal_coords=temporal_coords,
            location_coords=location_coords,
            mask_ratio=1.0 / x.shape[2],
            noise=noise,
        )

    mask_img_s = model.unpatchify(
        mask_s.unsqueeze(-1).repeat(1, 1, pred_s.shape[-1]).detach().cpu(),
        image_size=(x.shape[-2], x.shape[-1])
    )
    pred_img_s = model.unpatchify(
        pred_s.detach().cpu(),
        image_size=(x.shape[-2], x.shape[-1])
    )

    x_cpu = x.detach().cpu()
    rec_img_s = x_cpu.clone()
    rec_img_s[mask_img_s == 1] = pred_img_s[mask_img_s == 1]

    mae = torch.mean(torch.abs(rec_img_s[0, :, frame_to_mask] - x_cpu[0, :, frame_to_mask])).item()

    results.append({
        "masked_frame": frame_to_mask,
        "loss": float(loss_s),
        "mae": mae,
    })

for r in results:
    print(r)