data:
  patch_size: 16
  img_size: 448
  num_bands: 6

  tiles:
    - id: "tile_mexico_2018"
      base_dir: "/home/myid/syv35378/prithvi_repo"
      files:
        - "Mexico_HLS.S30.T13REM.2018026T173609.v2.0_cropped.tif"
        - "Mexico_HLS.S30.T13REM.2018106T172859.v2.0_cropped.tif"
        - "Mexico_HLS.S30.T13REM.2018201T172901.v2.0_cropped.tif"
        - "Mexico_HLS.S30.T13REM.2018266T173029.v2.0_cropped.tif"

model:
  device: "cuda"
  backbones:
    - name: "tiny"
      base_dir: "/home/myid/syv35378/prithvi_tiny"
      checkpoint: "Prithvi_EO_V2_tiny_TL.pt"
    - name: "100M"
      base_dir: "/home/myid/syv35378/prithvi_100M"
      checkpoint: "Prithvi_EO_V2_100M_TL.pt"
    - name: "300M"
      base_dir: "/home/myid/syv35378/prithvi_repo"
      checkpoint: "Prithvi_EO_V2_300M_TL.pt"
    - name: "600M"
      base_dir: "/home/myid/syv35378/prithvi_600M"
      checkpoint: "Prithvi_EO_V2_600M_TL.pt"

experiment:
  mask_positions:
    - "middle"
    - "endpoint"

  sequence_lengths: [3, 4]

  gap_types:
    - name: "regular"
      index_maps:
        3: [0, 1, 3]
        4: [0, 1, 2, 3]
    - name: "irregular"
      index_maps:
        3: [0, 1, 3]
        4: [0, 1, 2, 3]

  output_dir: "/home/myid/syv35378/Prithvi-Sandbox/outputs"
  save_plots: true
  save_plots_limit: 10